def login():
    text_log = Label(text="Congratulations! You have signed up succesfully!")
    text_enter_login = Label(text="Login:")
    enter_login = Entry()
    text_enter_password = Label(text='Password:')
    enter_password = Entry(show='*')
    button_enter = Button(text="Sign in", command=lambda: log_pass())
    text_log.pack()
    text_enter_login.pack()
    enter_login.pack()
    text_enter_password.pack()
    enter_password.pack()
    button_enter.pack()
